export { DialogTrigger } from './Dialog'
export { DialogPortal } from './Dialog'
export { DialogClose } from './Dialog'
export { DialogOverlay } from './Dialog'
export { DialogContent } from './Dialog'
export { DialogHeader } from './Dialog'
export { DialogFooter } from './Dialog'
export { DialogTitle } from './Dialog'
export { DialogDescription } from './Dialog'

export { default as Dialog } from './Dialog'
